const goods = [
  // Зеркала
  {
    id: 0,
    img: "img/goods/напольные-зеркала/1.png",
    name: "Kristin",
    desc: "Зеркало напольное",
    price: "120 000",
    color: "#AFCBFF", // пастельный голубой
    colorFilter: "голубой",
    category: "mirrors",
  },
  {
    id: 1,
    img: "img/goods/напольные-зеркала/2.png",
    name: "Colleen",
    desc: "Зеркало настенное",
    price: "130 000",
    color: "#C7E9FB", // пастельный синий
    colorFilter: "синий",
    category: "mirrors",
  },
  {
    id: 2,
    img: "img/goods/напольные-зеркала/3.png",
    name: "Coppelia",
    desc: "Зеркало напольное",
    price: "110 000",
    color: "#D2C9FF", // пастельный фиолетовый
    colorFilter: "лавандовый",
    category: "mirrors",
  },
  {
    id: 3,
    img: "img/goods/напольные-зеркала/4.png",
    name: "Coppelia",
    desc: "Зеркало напольное",
    price: "125 000",
    color: "#F4E3D4", // пастельный кремовый
    colorFilter: "оранжевый",
    category: "mirrors",
  },
  {
    id: 4,
    img: "img/goods/напольные-зеркала/5.png",
    name: "Artemide",
    desc: "Зеркало напольное",
    price: "140 000",
    color: "#C4E5F6", // пастельный бирюзовый
    colorFilter: "голубой",
    category: "mirrors",
  },
  {
    id: 5,
    img: "img/goods/напольные-зеркала/6.png",
    name: "Linen Dream",
    desc: "Зеркало напольное",
    price: "155 000",
    color: "#F8D9E3", // пастельный розовый
    colorFilter: "розовый",
    category: "mirrors",
  },
  {
    id: 6,
    img: "img/goods/напольные-зеркала/7.png",
    name: "Soft Whisper",
    desc: "Зеркало напольное",
    price: "135 000",
    color: "#DDEFEF", // пастельный мятный
    colorFilter: "голубой",
    category: "mirrors",
  },
  {
    id: 7,
    img: "img/goods/напольные-зеркала/8.png",
    name: "Morning Mist",
    desc: "Зеркало напольное",
    price: "145 000",
    color: "#F2E5B8", // пастельный желтый
    colorFilter: "оранжевый",
    category: "mirrors",
  },
  {
    id: 8,
    img: "img/goods/напольные-зеркала/9.png",
    name: "Calm Breeze",
    desc: "Зеркало напольное",
    price: "115 000",
    color: "#E3DDF0", // пастельный сиреневый
    colorFilter: "лавандовый",
    category: "mirrors",
  },
  {
    id: 9,
    img: "img/goods/напольные-зеркала/10.png",
    name: "Velvet Cloud",
    desc: "Зеркало напольное",
    price: "160 000",
    color: "#FAE8D3", // пастельный персиковый
    colorFilter: "оранжевый",
    category: "mirrors",
  },
  // Лампы
  {
    id: 10,
    img: "img/goods/торшеры -и-лампы/1.png",
    name: "Aubrey",
    desc: "Лампа настольная",
    price: "50 000",
    color: "#F0C9E8", // пастельный розовый
    colorFilter: "розовый",
    category: "lamps",
  },
  {
    id: 11,
    img: "img/goods/торшеры -и-лампы/2.png",
    name: "Leslie",
    desc: "Лампа настольная",
    price: "60 000",
    color: "#A9D7F5", // пастельный голубой
    colorFilter: "голубой",
    category: "lamps",
  },
  {
    id: 12,
    img: "img/goods/торшеры -и-лампы/3.png",
    name: "Darrell",
    desc: "Лампа настольная",
    price: "45 000",
    color: "#EFE7C5", // пастельный кремовый
    colorFilter: "оранжевый",
    category: "lamps",
  },
  {
    id: 13,
    img: "img/goods/торшеры -и-лампы/4.png",
    name: "Coppelia",
    desc: "Лампа настольная",
    price: "65 000",
    color: "#F1D8D9", // пастельный коралловый
    colorFilter: "розовый",
    category: "lamps",
  },
  {
    id: 14,
    img: "img/goods/торшеры -и-лампы/5.png",
    name: "Artemide",
    desc: "Лампа настольная",
    price: "55 000",
    color: "#D1E8F2", // пастельный бирюзовый
    colorFilter: "голубой",
    category: "lamps",
  },
  {
    id: 15,
    img: "img/goods/торшеры -и-лампы/6.png",
    name: "Linen Dream",
    desc: "Лампа настольная",
    price: "70 000",
    color: "#F7E3D1", // пастельный абрикосовый
    colorFilter: "оранжевый",
    category: "lamps",
  },
  {
    id: 16,
    img: "img/goods/торшеры -и-лампы/7.png",
    name: "Soft Whisper",
    desc: "Лампа настольная",
    price: "65 000",
    color: "#DAEFE6", // пастельный мятный
    colorFilter: "голубой",
    category: "lamps",
  },
  {
    id: 17,
    img: "img/goods/торшеры -и-лампы/8.png",
    name: "Morning Mist",
    desc: "Лампа настольная",
    price: "75 000",
    color: "#F5EAC0", // пастельный бежевый
    colorFilter: "оранжевый",
    category: "lamps",
  },
  {
    id: 18,
    img: "img/goods/торшеры -и-лампы/9.png",
    name: "Calm Breeze",
    desc: "Лампа настольная",
    price: "80 000",
    color: "#EDE2F1", // пастельный сиреневый
    colorFilter: "лавандовый",
    category: "lamps",
  },
  {
    id: 19,
    img: "img/goods/торшеры -и-лампы/10.png",
    name: "Velvet Cloud",
    desc: "Лампа настольная",
    price: "90 000",
    color: "#F4DFCA", // пастельный персиковый
    colorFilter: "оранжевый",
    category: "lamps",
  },
  // Столы
  {
    id: 20,
    img: "img/goods/столы-и-тумбы/1.png",
    name: "Aubrey",
    desc: "Зеркало напольное",
    price: "130 000",
    color: "#a5d4ff", // пастельный голубой
    colorFilter: "голубой",
    category: "tables",
  },
  {
    id: 21,
    img: "img/goods/столы-и-тумбы/2.png",
    name: "Leslie",
    desc: "Зеркало настенное",
    price: "670 000",
    color: "#8ECDFA", // пастельный синий
    colorFilter: "синий",
    category: "tables",
  },
  {
    id: 22,
    img: "img/goods/столы-и-тумбы/3.png",
    name: "Darrell",
    desc: "Зеркало напольное",
    price: "110 000",
    color: "#DACCF6", // пастельный фиолетовый
    colorFilter: "лавандовый",
    category: "tables",
  },
  {
    id: 23,
    img: "img/goods/столы-и-тумбы/4.png",
    name: "Coppelia",
    desc: "Зеркало напольное",
    price: "135 000",
    color: "#F1D7B6", // пастельный кремовый
    colorFilter: "оранжевый",
    category: "tables",
  },
  {
    id: 24,
    img: "img/goods/столы-и-тумбы/5.png",
    name: "Artemide",
    desc: "Зеркало напольное",
    price: "145 000",
    color: "#9CC1C8", // пастельный бирюзовый
    colorFilter: "голубой",
    category: "tables",
  },
  {
    id: 25,
    img: "img/goods/столы-и-тумбы/6.png",
    name: "Linen Dream",
    desc: "Зеркало напольное",
    price: "115 000",
    color: "#F8D6D9", // пастельный розовый
    colorFilter: "розовый",
    category: "tables",
  },
  {
    id: 26,
    img: "img/goods/столы-и-тумбы/7.png",
    name: "Soft Whisper",
    desc: "Зеркало напольное",
    price: "135 000",
    color: "#B2D4D4", // пастельный мятный
    colorFilter: "голубой",
    category: "tables",
  },
  {
    id: 27,
    img: "img/goods/столы-и-тумбы/8.png",
    name: "Morning Mist",
    desc: "Зеркало напольное",
    price: "140 000",
    color: "#F3E1B5", // пастельный желтый
    colorFilter: "оранжевый",
    category: "tables",
  },
  {
    id: 28,
    img: "img/goods/столы-и-тумбы/9.png",
    name: "Calm Breeze",
    desc: "Зеркало напольное",
    price: "120 000",
    color: "#DACBF4", // пастельный сиреневый
    colorFilter: "лавандовый",
    category: "tables",
  },
  {
    id: 29,
    img: "img/goods/столы-и-тумбы/10.png",
    name: "Velvet Cloud",
    desc: "Зеркало напольное",
    price: "150 000",
    color: "#F6DAC9", // пастельный персиковый
    colorFilter: "оранжевый",
    category: "tables",
  },

  // стулья
  {
    id: 30,
    img: "img/goods/кресла-и-стулья/1.png",
    name: "Aubrey",
    desc: "Зеркало напольное",
    price: "20 000",
    color: "#a5d4ff",
    colorFilter: "голубой",
    category: "chairs",
  },
  {
    id: 31,
    img: "img/goods/кресла-и-стулья/2.png",
    name: "Leslie",
    desc: "Зеркало настенное",
    price: "390 000",
    color: "#8ECDFA",
    colorFilter: "голубой",
    category: "chairs",
  },
  {
    id: 32,
    img: "img/goods/кресла-и-стулья/3.png",
    name: "Darrell",
    desc: "Зеркало напольное",
    price: "280 000",
    color: "#8ECDFA",
    colorFilter: "голубой",
    category: "chairs",
  },
  {
    id: 33,
    img: "img/goods/кресла-и-стулья/4.png",
    name: "Coppelia",
    desc: "Зеркало напольное",
    price: "820 000",
    color: "#FBE4CA",
    colorFilter: "оранжевый",
    category: "chairs",
  },
  {
    id: 34,
    img: "img/goods/кресла-и-стулья/5.png",
    name: "Artemide",
    desc: "Зеркало напольное",
    price: "480 000",
    color: "#a5d4ff",
    colorFilter: "голубой",
    category: "chairs",
  },
  {
    id: 35,
    img: "img/goods/кресла-и-стулья/6.png",
    name: "Linen Dream",
    desc: "Зеркало напольное",
    price: "120 000",
    color: "#F5E6E8",
    colorFilter: "розовый",
    category: "chairs",
  },
  {
    id: 36,
    img: "img/goods/кресла-и-стулья/7.png",
    name: "Soft Whisper",
    desc: "Зеркало напольное",
    price: "150 000",
    color: "#E6F2F0",
    colorFilter: "голубой",
    category: "chairs",
  },
  {
    id: 37,
    img: "img/goods/кресла-и-стулья/8.png",
    name: "Morning Mist",
    desc: "Зеркало напольное",
    price: "180 000",
    color: "#F3E5AB",
    colorFilter: "оранжевый",
    category: "chairs",
  },
  {
    id: 38,
    img: "img/goods/кресла-и-стулья/9.png",
    name: "Calm Breeze",
    desc: "Зеркало напольное",
    price: "900 000",
    color: "#EAE7F0",
    colorFilter: "голубой",
    category: "chairs",
  },
  {
    id: 39,
    img: "img/goods/кресла-и-стулья/10.png",
    name: "Velvet Cloud",
    desc: "Зеркало напольное",
    price: "110 000",
    color: "#F7F1E3",
    colorFilter: "розовый",
    category: "chairs",
  },
];

const articles = [
  {
    id: 0,
    number: "01",
    name: "Тренды 2024 года в дизайне интерьеров",
    date: "12 Марта 2024",
    img: "img/blog/1.jpg",
    readTime: "5",
    author: "Elena Smirnova",
  },
  {
    id: 1,
    number: "02",
    name: "Как выбрать идеальные кресла для вашего офиса",
    date: "18 Марта 2024",
    img: "img/blog/2.jpg",
    readTime: "4",
    author: "Maxim Petrov",
  },
  {
    id: 2,
    number: "03",
    name: "Ремонт и обновление старой мебели своими руками",
    date: "22 Марта 2024",
    img: "img/blog/3.jpg",
    readTime: "6",
    author: "Anna Ivanova",
  },
  {
    id: 3,
    number: "04",
    name: "Идеи для уютного декора вашего дома",
    date: "25 Марта 2024",
    img: "img/blog/1.jpg",
    readTime: "5",
    author: "Nikolai Sokolov",
  },
  {
    id: 4,
    number: "05",
    name: "Современные тенденции в использовании тканей",
    date: "30 Марта 2024",
    img: "img/blog/2.jpg",
    readTime: "7",
    author: "Irina Morozova",
  },
  {
    id: 5,
    number: "06",
    name: "Как выбрать мебель для маленьких квартир",
    date: "05 Апреля 2024",
    img: "img/blog/3.jpg",
    readTime: "4",
    author: "Dmitry Koval",
  },
  {
    id: 6,
    number: "07",
    name: "Влияние цвета на атмосферу в вашем доме",
    date: "10 Апреля 2024",
    img: "img/blog/1.jpg",
    readTime: "5",
    author: "Oksana Belova",
  },
  {
    id: 7,
    number: "08",
    name: "Рекомендации по выбору мебели для детей",
    date: "15 Апреля 2024",
    img: "img/blog/2.jpg",
    readTime: "6",
    author: "Sergey Mikhailov",
  },
  {
    id: 8,
    number: "09",
    name: "Советы по уходу за кожаной мебелью",
    date: "20 Апреля 2024",
    img: "img/blog/3.jpg",
    readTime: "4",
    author: "Olga Zaitseva",
  },
];
